package query;

public enum DbQueryType {
    CANDIDATE_BY_PARTY,
    VOTER_TOTAL_COUNT,
    VOTER_PER_STATE_COUNT,
    PARTY_ELECTED_BY_STATE,
    STATES_WITH_DIFFERENT_ELECTED_PARTY,
    ROW_COUNT
}
